# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWidow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(819, 894)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 791, 301))
        self.groupBox.setObjectName("groupBox")
        self.Table = QtWidgets.QTableWidget(self.groupBox)
        self.Table.setEnabled(True)
        self.Table.setGeometry(QtCore.QRect(20, 20, 751, 241))
        self.Table.setColumnCount(4)
        self.Table.setObjectName("Table")
        self.Table.setRowCount(0)
        self.PrintDB = QtWidgets.QPushButton(self.groupBox)
        self.PrintDB.setGeometry(QtCore.QRect(20, 270, 141, 23))
        self.PrintDB.setObjectName("PrintDB")
        self.SelectDB = QtWidgets.QComboBox(self.groupBox)
        self.SelectDB.setGeometry(QtCore.QRect(170, 270, 191, 22))
        self.SelectDB.setObjectName("SelectDB")
        self.SelectDB.addItem("")
        self.SelectDB.addItem("")
        self.SelectDB.addItem("")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 310, 311, 271))
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 20, 291, 151))
        self.groupBox_3.setObjectName("groupBox_3")
        self.TbParkName = QtWidgets.QLineEdit(self.groupBox_3)
        self.TbParkName.setGeometry(QtCore.QRect(10, 20, 113, 20))
        self.TbParkName.setObjectName("TbParkName")
        self.TbMaxDef = QtWidgets.QLineEdit(self.groupBox_3)
        self.TbMaxDef.setGeometry(QtCore.QRect(10, 50, 113, 20))
        self.TbMaxDef.setObjectName("TbMaxDef")
        self.TbMaxVIP = QtWidgets.QLineEdit(self.groupBox_3)
        self.TbMaxVIP.setGeometry(QtCore.QRect(10, 80, 113, 20))
        self.TbMaxVIP.setObjectName("TbMaxVIP")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(130, 20, 71, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(130, 50, 47, 13))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(130, 50, 161, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(130, 80, 131, 16))
        self.label_4.setObjectName("label_4")
        self.BTCreatePark = QtWidgets.QPushButton(self.groupBox_3)
        self.BTCreatePark.setGeometry(QtCore.QRect(10, 110, 261, 23))
        self.BTCreatePark.setObjectName("BTCreatePark")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 180, 291, 81))
        self.groupBox_4.setObjectName("groupBox_4")
        self.SelectDelPark = QtWidgets.QComboBox(self.groupBox_4)
        self.SelectDelPark.setGeometry(QtCore.QRect(10, 20, 271, 22))
        self.SelectDelPark.setObjectName("SelectDelPark")
        self.BtDelPark = QtWidgets.QPushButton(self.groupBox_4)
        self.BtDelPark.setGeometry(QtCore.QRect(10, 50, 271, 23))
        self.BtDelPark.setObjectName("BtDelPark")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(340, 310, 361, 181))
        self.groupBox_5.setObjectName("groupBox_5")
        self.SelectPark = QtWidgets.QComboBox(self.groupBox_5)
        self.SelectPark.setGeometry(QtCore.QRect(10, 20, 241, 22))
        self.SelectPark.setObjectName("SelectPark")
        self.TbCarNum = QtWidgets.QLineEdit(self.groupBox_5)
        self.TbCarNum.setGeometry(QtCore.QRect(10, 50, 141, 20))
        self.TbCarNum.setObjectName("TbCarNum")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setGeometry(QtCore.QRect(260, 20, 101, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_5)
        self.label_6.setGeometry(QtCore.QRect(160, 50, 141, 16))
        self.label_6.setObjectName("label_6")
        self.TbCarColor = QtWidgets.QLineEdit(self.groupBox_5)
        self.TbCarColor.setGeometry(QtCore.QRect(10, 80, 141, 20))
        self.TbCarColor.setObjectName("TbCarColor")
        self.label_7 = QtWidgets.QLabel(self.groupBox_5)
        self.label_7.setGeometry(QtCore.QRect(160, 80, 141, 16))
        self.label_7.setObjectName("label_7")
        self.BtParkCar = QtWidgets.QPushButton(self.groupBox_5)
        self.BtParkCar.setGeometry(QtCore.QRect(10, 110, 341, 23))
        self.BtParkCar.setObjectName("BtParkCar")
        self.PrintStack = QtWidgets.QPushButton(self.groupBox_5)
        self.PrintStack.setGeometry(QtCore.QRect(10, 140, 341, 31))
        self.PrintStack.setObjectName("PrintStack")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(290, 590, 361, 121))
        self.groupBox_6.setObjectName("groupBox_6")
        self.TbCarNumLeave = QtWidgets.QLineEdit(self.groupBox_6)
        self.TbCarNumLeave.setGeometry(QtCore.QRect(10, 50, 141, 20))
        self.TbCarNumLeave.setObjectName("TbCarNumLeave")
        self.label_9 = QtWidgets.QLabel(self.groupBox_6)
        self.label_9.setGeometry(QtCore.QRect(160, 50, 141, 16))
        self.label_9.setObjectName("label_9")
        self.BtLeaveParkCar = QtWidgets.QPushButton(self.groupBox_6)
        self.BtLeaveParkCar.setGeometry(QtCore.QRect(10, 80, 341, 23))
        self.BtLeaveParkCar.setObjectName("BtLeaveParkCar")
        self.SelectParkLeave = QtWidgets.QComboBox(self.groupBox_6)
        self.SelectParkLeave.setGeometry(QtCore.QRect(10, 20, 241, 22))
        self.SelectParkLeave.setObjectName("SelectParkLeave")
        self.label_8 = QtWidgets.QLabel(self.groupBox_6)
        self.label_8.setGeometry(QtCore.QRect(260, 20, 101, 16))
        self.label_8.setObjectName("label_8")
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 590, 261, 111))
        self.groupBox_7.setObjectName("groupBox_7")
        self.TbCarNumVIP = QtWidgets.QLineEdit(self.groupBox_7)
        self.TbCarNumVIP.setGeometry(QtCore.QRect(10, 20, 113, 20))
        self.TbCarNumVIP.setObjectName("TbCarNumVIP")
        self.label_10 = QtWidgets.QLabel(self.groupBox_7)
        self.label_10.setGeometry(QtCore.QRect(130, 20, 131, 16))
        self.label_10.setObjectName("label_10")
        self.BtAddVIP = QtWidgets.QPushButton(self.groupBox_7)
        self.BtAddVIP.setGeometry(QtCore.QRect(10, 50, 241, 23))
        self.BtAddVIP.setObjectName("BtAddVIP")
        self.BtDelVIP = QtWidgets.QPushButton(self.groupBox_7)
        self.BtDelVIP.setGeometry(QtCore.QRect(10, 80, 241, 23))
        self.BtDelVIP.setObjectName("BtDelVIP")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 819, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Базы данных"))
        self.PrintDB.setText(_translate("MainWindow", "Вывести Базу Данных"))
        self.SelectDB.setItemText(0, _translate("MainWindow", "Вьезд выезд"))
        self.SelectDB.setItemText(1, _translate("MainWindow", "Парковочные места"))
        self.SelectDB.setItemText(2, _translate("MainWindow", "Лист VIP номеров"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Парковки"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Создать"))
        self.label.setText(_translate("MainWindow", "Имя парковки"))
        self.label_3.setText(_translate("MainWindow", "Макс. кол-во обычных мест"))
        self.label_4.setText(_translate("MainWindow", "Макс. кол-во VIP мест"))
        self.BTCreatePark.setText(_translate("MainWindow", "Создать парковку"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Удалить"))
        self.BtDelPark.setText(_translate("MainWindow", "Удалить пакровку"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Припарковать"))
        self.label_5.setText(_translate("MainWindow", "Выбор парковки"))
        self.label_6.setText(_translate("MainWindow", "Автомобильный номер"))
        self.label_7.setText(_translate("MainWindow", "Цвет автомобиля"))
        self.BtParkCar.setText(_translate("MainWindow", "Припарковать автомобиль"))
        self.PrintStack.setText(_translate("MainWindow", "Вывести информацию о парковке (выезд наверху)"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Выехать с парковки"))
        self.label_9.setText(_translate("MainWindow", "Автомобильный номер"))
        self.BtLeaveParkCar.setText(_translate("MainWindow", "Выехать с парковки"))
        self.label_8.setText(_translate("MainWindow", "Выбор парковки"))
        self.groupBox_7.setTitle(_translate("MainWindow", "VIP"))
        self.label_10.setText(_translate("MainWindow", "Автомобильный номер"))
        self.BtAddVIP.setText(_translate("MainWindow", "Добавить автомобиль в VIP лист"))
        self.BtDelVIP.setText(_translate("MainWindow", "Убрать автомобиль из VIP листа"))
